from enum import Enum

class Type(Enum):
    TILE_GRASS    = 0
    TILE_WATER    = 1
    TILE_FOREST   = 2
    TILE_COASTN   = 3
    TILE_COASTE   = 4
    TILE_COASTS   = 5
    TILE_COASTW   = 6
    TILE_COASTNE  = 7
    TILE_COASTSE  = 8
    TILE_COASTSW  = 9
    TILE_COASTNW  = 10
    TILE_COASTNE2 = 11
    TILE_COASTSE2 = 12
    TILE_COASTSW2 = 13
    TILE_COASTNW2 = 14
    TILE_ROCKN    = 15
    TILE_ROCKE    = 16
    TILE_ROCKS    = 17
    TILE_ROCKW    = 18
    TILE_ROCKNE   = 19
    TILE_ROCKSE   = 20
    TILE_ROCKSW   = 21
    TILE_ROCKNW   = 22
    TILE_FORESTN   = 23
    TILE_FORESTE   = 24
    TILE_FORESTS   = 25
    TILE_FORESTW   = 26
    TILE_FORESTNE  = 27
    TILE_FORESTSE  = 28
    TILE_FORESTSW  = 29
    TILE_FORESTNW  = 30
    TILE_FORESTNE2 = 31
    TILE_FORESTSE2 = 32
    TILE_FORESTSW2 = 33
    TILE_FORESTNW2 = 34