from src.enums.type import Type

SPRITES = {
    Type.TILE_GRASS : "▓▓",
    Type.TILE_WATER : "░░",
    Type.TILE_FOREST: "╫╫",
    Type.TILE_COASTN  : "▒▒",
    Type.TILE_COASTE  : "▒▒",
    Type.TILE_COASTS  : "▒▒",
    Type.TILE_COASTW  : "▒▒",
    Type.TILE_COASTNE : "▒▒",
    Type.TILE_COASTSE : "▒▒",
    Type.TILE_COASTSW : "▒▒",
    Type.TILE_COASTNW : "▒▒",
    Type.TILE_COASTNE2: "▒▒",
    Type.TILE_COASTSE2: "▒▒",
    Type.TILE_COASTSW2: "▒▒",
    Type.TILE_COASTNW2: "▒▒",
    Type.TILE_FORESTN  : "╫╫",
    Type.TILE_FORESTE  : "╫╫",
    Type.TILE_FORESTS  : "╫╫",
    Type.TILE_FORESTW  : "╫╫",
    Type.TILE_FORESTNE : "╫╫",
    Type.TILE_FORESTSE : "╫╫",
    Type.TILE_FORESTSW : "╫╫",
    Type.TILE_FORESTNW : "╫╫",
    Type.TILE_FORESTNE2: "╫╫",
    Type.TILE_FORESTSE2: "╫╫",
    Type.TILE_FORESTSW2: "╫╫",
    Type.TILE_FORESTNW2: "╫╫",
    Type.TILE_ROCKN   : "██",
    Type.TILE_ROCKE   : "██",
    Type.TILE_ROCKS   : "██",
    Type.TILE_ROCKW   : "██",
    Type.TILE_ROCKNE  : "██",
    Type.TILE_ROCKSE  : "██",
    Type.TILE_ROCKSW  : "██",
    Type.TILE_ROCKNW  : "██",
}